### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by strasin** [LielXD/CS2-WeaponPaints-Website#80]
http://goplay.az/skins/skins/

I choose a weapon for example five-seven , when choosing a skin (clicking on the skin) it gives an error 
HTTP ERROR 500
![Uploading asdasdas.png…]()

**Comment by strasin** [comment]
root@zaur-Z10PA-D8-Series:~# sudo tail -f /var/log/apache2/error.log
[Tue Dec 03 00:03:34.929692 2024] [php:warn] [pid 382548] [client 82.194.26.212:10157] PHP Warning:  Attempt to read property "image" on bool in /var/www/html/skins/skins/index.php on line 694, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:03:34.929732 2024] [php:warn] [pid 382548] [client 82.194.26.212:10157] PHP Warning:  Attempt to read property "weapon_name" on bool in /var/www/html/skins/skins/index.php on line 694, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:03:34.929747 2024] [php:warn] [pid 382548] [client 82.194.26.212:10157] PHP Warning:  Attempt to read property "agent_name" on bool in /var/www/html/skins/skins/index.php on line 700, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:03:42.814740 2024] [php:warn] [pid 382549] [client 82.194.26.212:62218] PHP Warning:  Undefined property: stdClass::$mvp in /var/www/html/skins/skins/index.php on line 373, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:03:46.402743 2024] [php:warn] [pid 382897] [client 82.194.26.212:62245] PHP Warning:  Undefined property: stdClass::$weapon_name in /var/www/html/skins/skins/index.php on line 694, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:03:49.057120 2024] [php:error] [pid 382897] [client 82.194.26.212:62245] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/html/skins/skins/index.php:146\nStack trace:\n#0 /var/www/html/skins/skins/index.php(146): PDOStatement->execute()\n#1 {main}\n  thrown in /var/www/html/skins/skins/index.php on line 146, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:03:50.331917 2024] [php:warn] [pid 382545] [client 82.194.26.212:62246] PHP Warning:  Undefined property: stdClass::$mvp in /var/www/html/skins/skins/index.php on line 373, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:03:59.201385 2024] [php:warn] [pid 382546] [client 82.194.26.212:10175] PHP Warning:  Undefined property: stdClass::$weapon_name in /var/www/html/skins/skins/index.php on line 694, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:04:05.976653 2024] [php:error] [pid 382547] [client 82.194.26.212:62256] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/html/skins/skins/index.php:146\nStack trace:\n#0 /var/www/html/skins/skins/index.php(146): PDOStatement->execute()\n#1 {main}\n  thrown in /var/www/html/skins/skins/index.php on line 146, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:04:08.516900 2024] [php:warn] [pid 382549] [client 82.194.26.212:10181] PHP Warning:  Undefined property: stdClass::$mvp in /var/www/html/skins/skins/index.php on line 373, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:07:42.906857 2024] [php:warn] [pid 382547] [client 82.194.26.212:10297] PHP Warning:  Undefined property: stdClass::$mvp in /var/www/html/skins/skins/index.php on line 373, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:07:45.261770 2024] [php:warn] [pid 382547] [client 82.194.26.212:10297] PHP Warning:  Undefined property: stdClass::$weapon_name in /var/www/html/skins/skins/index.php on line 694, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:07:46.510803 2024] [php:error] [pid 384131] [client 82.194.26.212:62370] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/html/skins/skins/index.php:146\nStack trace:\n#0 /var/www/html/skins/skins/index.php(146): PDOStatement->execute()\n#1 {main}\n  thrown in /var/www/html/skins/skins/index.php on line 146, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:07:48.664787 2024] [php:error] [pid 385455] [client 82.194.26.212:10303] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/html/skins/skins/index.php:146\nStack trace:\n#0 /var/www/html/skins/skins/index.php(146): PDOStatement->execute()\n#1 {main}\n  thrown in /var/www/html/skins/skins/index.php on line 146, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:07:50.068580 2024] [php:error] [pid 382548] [client 82.194.26.212:10307] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/html/skins/skins/index.php:146\nStack trace:\n#0 /var/www/html/skins/skins/index.php(146): PDOStatement->execute()\n#1 {main}\n  thrown in /var/www/html/skins/skins/index.php on line 146, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:07:54.804448 2024] [php:error] [pid 382897] [client 82.194.26.212:10309] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/html/skins/skins/index.php:146\nStack trace:\n#0 /var/www/html/skins/skins/index.php(146): PDOStatement->execute()\n#1 {main}\n  thrown in /var/www/html/skins/skins/index.php on line 146, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:08:01.114695 2024] [php:warn] [pid 382546] [client 82.194.26.212:10311] PHP Warning:  Undefined property: stdClass::$mvp in /var/www/html/skins/skins/index.php on line 373, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:09:58.023782 2024] [php:warn] [pid 387014] [client 82.194.26.212:62436] PHP Warning:  Undefined property: stdClass::$mvp in /var/www/html/skins/skins/index.php on line 373, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:10:01.341877 2024] [php:warn] [pid 387014] [client 82.194.26.212:62436] PHP Warning:  Undefined property: stdClass::$weapon_name in /var/www/html/skins/skins/index.php on line 694, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:10:02.595495 2024] [php:error] [pid 387014] [client 82.194.26.212:62436] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/html/skins/skins/index.php:146\nStack trace:\n#0 /var/www/html/skins/skins/index.php(146): PDOStatement->execute()\n#1 {main}\n  thrown in /var/www/html/skins/skins/index.php on line 146, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:10:03.593765 2024] [php:warn] [pid 387022] [client 82.194.26.212:10371] PHP Warning:  Undefined property: stdClass::$mvp in /var/www/html/skins/skins/index.php on line 373, referer: http://goplay.az/skins/skins/
[Tue Dec 03 00:20:02.603715 2024] [php:error] [pid 387030] [client 82.194.26.212:53248] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/html/skins/skins/index.php:146\nStack trace:\n#0 /var/www/html/skins/skins/index.php(146): PDOStatement->execute()\n#1 {main}\n  thrown in /var/www/html/skins/skins/index.php on line 146, referer: http://goplay.az/skins/skins/

**Comment by strasin** [comment]
solved with install old plugin version
https://github.com/Nereziel/cs2-WeaponPaints/releases/tag/build-297

**Comment by haqoff** [comment]
you can find the fix here: https://github.com/haqoff/CS2-WeaponPaints-Website

**Comment by LielXD** [comment]
Fixed with v2.0.0.
