### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by Matsakan** [LielXD/CS2-WeaponPaints-Website#81]
When I select some skins, I get this error:
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/server31443/data/www/vipcss2.cshost.site/weapons/skins/index.php:240 Stack trace: #0 /var/www/server31443/data/www/vipcss2.cshost.site/weapons/skins/index.php(240): PDOStatement->execute(Array) #1 {main} thrown in /var/www/server31443/data/www/vipcss2.cshost.site/weapons/skins/index.php on line 240

What can be done about this? How to fix it?
Thank you.

**Comment by strasin** [comment]
same error 'weapon_team' but line 146
contact with me discord "strasin" id 274297562377224194

**Comment by Matsakan** [comment]
> та же ошибка 'weapon_team', но строка 146 свяжитесь со мной в дискорде "strasin" id 274297562377224194

Sent a request to Discord

**Comment by Matsakan** [comment]
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'weapon_team' doesn't have a default value in /var/www/server31443/data/www/vipcss2.cshost.site/weapons/skins/index.php:146 Stack trace: #0 /var/www/server31443/data/www/vipcss2.cshost.site/weapons/skins/index.php(146): PDOStatement->execute(Array) #1 {main} thrown in /var/www/server31443/data/www/vipcss2.cshost.site/weapons/skins/index.php on line 146

Это на перчатках

**Comment by haqoff** [comment]
you can find the fix here: https://github.com/haqoff/CS2-WeaponPaints-Website

**Comment by LielXD** [comment]
Fixed with v2.0.0.
